# replace default config

# multipass: true
# full: true

plugins:

  # - name
  #
  # or:
  # - name: false
  # - name: true
  #
  # or:
  # - name:
  #     param1: 1
  #     param2: 2

  - removeDoctype : true
  - removeXMLProcInst  : true
  - removeComments : true
  - removeMetadata : true
  - removeEditorsNSData : true
  - cleanupAttrs: true
  - minifyStyles: true
  - convertStyleToAttrs : true
  - cleanupIDs: true
  - removeRasterImages : true
  - removeUselessDefs : true
  - cleanupNumericValues : true
  - cleanupListOfValues : true
  - convertColors : false
  - removeUnknownsAndDefaults : true
  - removeNonInheritableGroupAttrs : true
  - removeUselessStrokeAndFill : true
  - removeViewBox : false
  - cleanupEnableBackground : true
  - removeHiddenElems : true
  - removeEmptyText : true
  - convertShapeToPath : false
  - moveElemsAttrsToGroup : true
  - moveGroupAttrsToElems  : true
  - collapseGroups : true
  - convertPathData : true
  - convertTransform : true
  - removeEmptyAttrs : true
  - removeEmptyContainers : true
  - mergePaths : true
  - removeUnusedNS : true
  - transformsWithOnePath : false
  - sortAttrs : true
  - removeTitle : true
  - removeDesc : true
  - removeDimensions : false
  - removeAttrs: true
  - addClassesToSVGElement: false
  - removeStyleElement: true
